[package]
name = "busychild"
version = "0.1.0"
authors = ["h0mbre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
procfs = "0.8.0"
chrono = "0.4.13"
glob = "0.3"
